#!/usr/bin/env node
/**
 * @verobee/spec — DTCG schema package build.
 *
 * The spec package supplies the schema only (slot names + types, no values).
 * This build:
 *   1. Validates JSON shape (every entry has $type, no $value).
 *   2. Emits TypeScript types listing every slot path (CssVarName, TokenPath).
 *   3. Copies tokens to dist/ for downstream consumers.
 *
 * NOTE: during migration we also keep the spec inline in @verobee/design;
 * this package becomes the canonical source after Phase H.
 */
import { readFile, writeFile, mkdir, readdir, copyFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const TOKENS_DIR = join(ROOT, 'tokens');
const DIST_DIR = join(ROOT, 'dist');

async function* walk(dir) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(full);
    else if (entry.name.endsWith('.json')) yield full;
  }
}

function flattenPaths(obj, prefix = []) {
  const out = [];
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith('$')) continue;
    const path = [...prefix, k];
    if (v && typeof v === 'object' && '$type' in v) out.push(path);
    else if (v && typeof v === 'object') out.push(...flattenPaths(v, path));
  }
  return out;
}

function pathToCssVar(path) {
  return '--vds-' + path.join('-').toLowerCase();
}

async function main() {
  console.log('@verobee/spec — build');
  await mkdir(DIST_DIR, { recursive: true });
  await mkdir(join(DIST_DIR, 'tokens'), { recursive: true });
  await mkdir(join(DIST_DIR, 'types'), { recursive: true });

  const allPaths = [];
  for await (const file of walk(TOKENS_DIR)) {
    const json = JSON.parse(await readFile(file, 'utf-8'));
    const rel = file.slice(TOKENS_DIR.length + 1);
    await mkdir(join(DIST_DIR, 'tokens', dirname(rel)), { recursive: true });
    await copyFile(file, join(DIST_DIR, 'tokens', rel));
    allPaths.push(...flattenPaths(json));
  }

  const cssVars = allPaths.map(pathToCssVar).sort();
  const tokenPaths = allPaths.map((p) => p.join('.')).sort();

  const dts = `// Auto-generated by @verobee/spec build. Do not edit.
export type CssVarName =
  | ${cssVars.map((v) => `"${v}"`).join('\n  | ')};

export type TokenPath =
  | ${tokenPaths.map((p) => `"${p}"`).join('\n  | ')};
`;
  await writeFile(join(DIST_DIR, 'types', 'tokens.d.ts'), dts);

  console.log(`  emitted ${cssVars.length} CssVarName, ${tokenPaths.length} TokenPath types`);
  console.log('done');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
