#!/usr/bin/env node
/**
 * @verobee/theme-verobase — brand theme build.
 *
 * Reads light + dark token JSONs, resolves primitive references via
 * @verobee/primitive, emits a single theme CSS file with light-dark()
 * function for mode switching.
 *
 * Output: dist/css/verobase.css + .min.css (+ Brotli sibling later via
 * verodesign-wide compress step or per-package).
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(dirname(fileURLToPath(import.meta.url)));
const BRAND = 'verobase';
const TOKENS_DIR = join(ROOT, 'tokens');
const DIST_DIR = join(ROOT, 'dist');

// Locate primitive tokens (workspace-resolved). Falls back to the legacy
// design package during migration.
async function loadPrimitives() {
  const candidates = [
    join(ROOT, '..', 'primitive', 'tokens', 'primitive'),
    join(ROOT, '..', 'design', 'tokens', 'primitive'),
  ];
  for (const dir of candidates) {
    try {
      const files = await readDir(dir);
      const map = {};
      for (const f of files) {
        const json = JSON.parse(await readFile(join(dir, f), 'utf-8'));
        deepMerge(map, json);
      }
      return map;
    } catch {}
  }
  throw new Error('Cannot locate primitive tokens');
}

import { readdir as readDir } from 'node:fs/promises';

function deepMerge(target, source) {
  for (const k of Object.keys(source)) {
    if (typeof source[k] === 'object' && source[k] !== null && !Array.isArray(source[k])) {
      target[k] = target[k] ?? {};
      deepMerge(target[k], source[k]);
    } else target[k] = source[k];
  }
}

function getByPath(obj, path) {
  return path.split('.').reduce((a, k) => (a ? a[k] : undefined), obj);
}

function resolveRef(value, primitives) {
  if (typeof value !== 'string') return value;
  return value.replace(/\{([^}]+)\}/g, (_, refPath) => {
    const ref = getByPath(primitives, refPath);
    if (ref && typeof ref === 'object' && '$value' in ref) {
      return resolveRef(ref.$value, primitives);
    }
    return _;
  });
}

function flatten(obj, prefix = []) {
  const out = [];
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith('$')) continue;
    if (v && typeof v === 'object' && '$value' in v) {
      out.push({ path: [...prefix, k], value: v.$value });
    } else if (v && typeof v === 'object') {
      out.push(...flatten(v, [...prefix, k]));
    }
  }
  return out;
}

const cssVar = (path) => '--vds-' + path.join('-').toLowerCase();

function renderMode(modeTokens, primitives) {
  return modeTokens
    .map((t) => `    ${cssVar(t.path)}: ${resolveRef(t.value, primitives)};`)
    .join('\n');
}

async function main() {
  console.log(`@verobee/theme-${BRAND} — build`);
  await mkdir(join(DIST_DIR, 'css'), { recursive: true });
  await mkdir(join(DIST_DIR, 'types'), { recursive: true });

  const primitives = await loadPrimitives();
  const light = JSON.parse(await readFile(join(TOKENS_DIR, `${BRAND}-light.json`), 'utf-8'));
  const dark = JSON.parse(await readFile(join(TOKENS_DIR, `${BRAND}-dark.json`), 'utf-8'));

  const lightFlat = flatten(light);
  const darkFlat = flatten(dark);

  const css = `@layer vds-tokens {
  [data-theme="${BRAND}"],
  [data-theme="${BRAND}"][data-mode="light"] {
${renderMode(lightFlat, primitives)}
  }
  [data-theme="${BRAND}"][data-mode="dark"] {
${renderMode(darkFlat, primitives)}
  }
}
`;
  await writeFile(join(DIST_DIR, 'css', `${BRAND}.css`), css);
  await writeFile(join(DIST_DIR, 'css', `${BRAND}.min.css`), css.replace(/\s+/g, ' '));

  // Type emit — slot names available in this theme
  const slots = Array.from(new Set([...lightFlat, ...darkFlat].map((t) => t.path.join('.')))).sort();
  const dts = `// Auto-generated by @verobee/theme-${BRAND}. Do not edit.
export type ThemeTokenPath =
  | ${slots.map((s) => `"${s}"`).join('\n  | ')};

export type ThemeCssVar =
  | ${slots.map((s) => `"--vds-${s.replace(/\./g, '-').toLowerCase()}"`).join('\n  | ')};

export const THEME_NAME = "${BRAND}" as const;
`;
  await writeFile(join(DIST_DIR, 'types', 'tokens.d.ts'), dts);

  console.log(`  light=${lightFlat.length} dark=${darkFlat.length} slots`);
  console.log('done');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
